# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: your_development_database_name

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>